run:
  timeout: 5m
  issues-exit-code: 1
  tests: true
  modules-download-mode: readonly

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters:
  enable:
    - asciicheck
    - bodyclose
    - cyclop
    - dupl
    - durationcheck
    - errcheck
    - errorlint
    - exhaustive
    - exportloopref
    - forbidigo
    - forcetypeassert
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - gofmt
    - gofumpt
    - goheader
    - goimports
    - golint
    - gomnd
    - gomodguard
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - interfacer
    - lll
    - makezero
    - misspell
    - nakedret
    - nestif
    - nilerr
    - nlreturn
    - noctx
    - prealloc
    - predeclared
    - revive
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - structcheck
    - stylecheck
    - thelper
    - tparallel
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - wastedassign
    - whitespace
    - wsl

linters-settings:
  cyclop:
    max-complexity: 15
  
  gocognit:
    min-complexity: 20
  
  gocyclo:
    min-complexity: 15
  
  goconst:
    min-len: 3
    min-occurrences: 3
  
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
  
  gofumpt:
    extra-rules: true
  
  gomnd:
    settings:
      mnd:
        checks:
          - argument
          - case
          - condition
          - operation
          - return
  
  lll:
    line-length: 120
  
  misspell:
    locale: US
  
  nakedret:
    max-func-lines: 30
  
  nestif:
    min-complexity: 5
  
  nlreturn:
    block-size: 2
  
  prealloc:
    simple: true
    range-loops: true
    for-loops: false
  
  revive:
    rules:
      - name: exported
        arguments:
          - "checkPrivateReceivers"
          - "sayRepetitiveInsteadOfStutters"

issues:
  exclude-use-default: false
  exclude:
    - "should have a package comment"
    - "don't use an underscore in package name"
  
  exclude-rules:
    - path: _test\.go
      linters:
        - gomnd
        - goconst
        - dupl
    
    - path: cmd/
      linters:
        - gochecknoinits
    
    - source: "//go:generate"
      linters:
        - lll

  max-issues-per-linter: 0
  max-same-issues: 0 